package com.softdesign.devintensive.data.storage.models;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.softdesign.devintensive.data.storage.models.Repository;
import com.softdesign.devintensive.data.storage.models.UserDb;

import com.softdesign.devintensive.data.storage.models.RepositoryDao;
import com.softdesign.devintensive.data.storage.models.UserDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig repositoryDaoConfig;
    private final DaoConfig userDbDaoConfig;

    private final RepositoryDao repositoryDao;
    private final UserDbDao userDbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        repositoryDaoConfig = daoConfigMap.get(RepositoryDao.class).clone();
        repositoryDaoConfig.initIdentityScope(type);

        userDbDaoConfig = daoConfigMap.get(UserDbDao.class).clone();
        userDbDaoConfig.initIdentityScope(type);

        repositoryDao = new RepositoryDao(repositoryDaoConfig, this);
        userDbDao = new UserDbDao(userDbDaoConfig, this);

        registerDao(Repository.class, repositoryDao);
        registerDao(UserDb.class, userDbDao);
    }
    
    public void clear() {
        repositoryDaoConfig.getIdentityScope().clear();
        userDbDaoConfig.getIdentityScope().clear();
    }

    public RepositoryDao getRepositoryDao() {
        return repositoryDao;
    }

    public UserDbDao getUserDbDao() {
        return userDbDao;
    }

}
